server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_URL}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
    open-in-view: false

kafka:
  ms-client:
    topic-name: ${SPRING_KAFKA_MS_CLIENT_TOPIC_NAME}